import { AgentAnalysis } from "../../domain/entities/AgentAnalysis";
import { config } from "../../config";
import { AgentType } from "../../shared/enums";
import { agentSystemPrompts } from "./prompts";

export interface DecisionInput {
  title: string;
  context: string;
  horizon: string;
  riskLevel: string;
}

type ModelResponse = {
  analysis?: unknown;
  recommendation?: unknown;
  conditions?: unknown;
  risks?: unknown;
  confidence?: unknown;
};

export class LlmClient {
  async analyze(agentType: AgentType, input: DecisionInput): Promise<Omit<AgentAnalysis, "decisionId">> {
    if (!config.openAiApiKey) {
      return this.synthetic(agentType, input, "missing_api_key");
    }

    try {
      const content = await this.callOpenAi(agentType, input);
      const parsed = this.parseModelResponse(content, agentType, input);
      return parsed;
    } catch {
      return this.synthetic(agentType, input, "api_fallback");
    }
  }

  private async callOpenAi(agentType: AgentType, input: DecisionInput): Promise<string> {
    const system = agentSystemPrompts[agentType];
    const userPrompt = [
      "Analyze this strategic decision.",
      `Title: ${input.title}`,
      `Context: ${input.context}`,
      `Horizon: ${input.horizon}`,
      `Risk level: ${input.riskLevel}`,
      "Return ONLY valid JSON with keys:",
      "analysis: string",
      "recommendation: GO | NO_GO | CONDITIONAL_GO",
      "conditions: string[]",
      "risks: [{label:string,severity:number(0-100),rationale:string}] (at least 3)",
      "confidence: number(0-100)"
    ].join("\n");

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${config.openAiApiKey}`
      },
      body: JSON.stringify({
        model: config.openAiModel,
        temperature: 0.2,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: system },
          { role: "user", content: userPrompt }
        ]
      })
    });

    if (!response.ok) {
      throw new Error(`OpenAI request failed with status ${response.status}`);
    }

    const payload = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };

    const content = payload.choices?.[0]?.message?.content;
    if (!content) throw new Error("Empty model response");
    return content;
  }

  private parseModelResponse(content: string, agentType: AgentType, input: DecisionInput): Omit<AgentAnalysis, "decisionId"> {
    let raw: ModelResponse | null = null;

    try {
      raw = JSON.parse(content) as ModelResponse;
    } catch {
      const match = content.match(/\{[\s\S]*\}/);
      if (match) {
        raw = JSON.parse(match[0]) as ModelResponse;
      }
    }

    if (!raw) return this.synthetic(agentType, input, "parse_fallback");

    const recommendation = this.normalizeRecommendation(raw.recommendation);
    const confidence = this.clampNumber(raw.confidence, 70);

    const risks = Array.isArray(raw.risks)
      ? raw.risks
          .map((risk: any, idx) => ({
            label: typeof risk?.label === "string" ? risk.label : `${agentType}-risk-${idx + 1}`,
            severity: this.clampNumber(risk?.severity, 60),
            rationale: typeof risk?.rationale === "string" ? risk.rationale : "Rationale non fournie par le modele."
          }))
          .slice(0, 8)
      : [];

    while (risks.length < 3) {
      risks.push({
        label: `${agentType}-risk-${risks.length + 1}`,
        severity: 55,
        rationale: "Risque complete automatiquement car la reponse etait incomplete."
      });
    }

    return {
      agentType,
      analysis: typeof raw.analysis === "string" ? raw.analysis : `${agentType.toUpperCase()} analysis generated by model.`,
      recommendation,
      conditions: Array.isArray(raw.conditions) ? raw.conditions.filter((c): c is string => typeof c === "string") : [],
      risks,
      confidence
    };
  }

  private normalizeRecommendation(value: unknown): "GO" | "NO_GO" | "CONDITIONAL_GO" {
    if (value === "GO" || value === "NO_GO" || value === "CONDITIONAL_GO") return value;
    return "CONDITIONAL_GO";
  }

  private clampNumber(value: unknown, fallback: number): number {
    if (typeof value !== "number" || Number.isNaN(value)) return fallback;
    return Math.max(0, Math.min(100, Math.round(value)));
  }

  private synthetic(agentType: AgentType, input: DecisionInput, reason: string): Omit<AgentAnalysis, "decisionId"> {
    const syntheticSeverity = this.syntheticSeverity(agentType, input);
    return {
      agentType,
      analysis: `${agentType.toUpperCase()} analysis of ${input.title}: ${input.context.slice(0, 220)} [${reason}]`,
      recommendation: syntheticSeverity > 70 ? "NO_GO" : syntheticSeverity > 55 ? "CONDITIONAL_GO" : "GO",
      conditions: syntheticSeverity > 55 ? ["Valider hypotheses critiques avant execution", "Mettre un plan de mitigation trimestriel"] : [],
      risks: [
        { label: `${agentType}-risk-1`, severity: syntheticSeverity, rationale: `Primary ${agentType} concern identified.` },
        { label: `${agentType}-risk-2`, severity: Math.min(100, syntheticSeverity + 8), rationale: "Secondary dependency risk." },
        { label: `${agentType}-risk-3`, severity: Math.max(0, syntheticSeverity - 10), rationale: "Execution variance risk." }
      ],
      confidence: 72
    };
  }

  private syntheticSeverity(agentType: AgentType, input: DecisionInput): number {
    const base = input.riskLevel === "high" ? 72 : input.riskLevel === "medium" ? 58 : 44;
    const modifier = agentType === "legal" ? 7 : agentType === "risk" ? 9 : agentType === "growth" ? -4 : 0;
    return Math.max(0, Math.min(100, base + modifier));
  }
}
